In [ ]:
import numpy as np
import pandas as pd

In [ ]:
class regresionlineal:
  def __init__(self,x,y):
    self.x=x
    self.y=y
  def beta(self):
    bet=np.linalg.inv(self.x.T@self.x)@(self.x.T@self.y)
    return bet
  def errore(self):
    bet=self.beta()
    yest=self.x@bet
    errorest=self.y-yest
    n,k=x.shape
    var=(errorest.T@errorest)/(n-k)
    errorestandar=(np.diagonal(var*np.linalg.inv(self.x.T@self.x)))**(1/2)
    return errorestandar.reshape(-1,1)
  def testadistico(self):
    estadisticot=((self.beta().reshape(-1,1))/self.errore())
    return estadisticot
  def intervaloc(self):
    limsup=self.beta()+1.96*self.errore()
    liminf=self.beta()-1.96*self.errore()
    for i, j in zip(liminf, limsup):
      print(i[0], j[0])
    

In [ ]:
!pip install wooldridge

In [ ]:
import wooldridge as wd
crim=wd.data("crime1")
crim=crim[["narr86","pcnv","avgsen","tottime","inc86"]]

In [ ]:
crim

narr86  pcnv     avgsen    tottime       inc86
0          0  0.38  17.600000  35.200001    0.000000
1          2  0.44   0.000000   0.000000    0.800000
2          1  0.33  22.799999  22.799999    0.000000
3          2  0.25   0.000000   0.000000    8.800000
4          1  0.00   0.000000   0.000000    8.100000
...      ...   ...        ...        ...         ...
2720       1  0.00   0.000000   0.000000    0.000000
2721       0  0.00   0.000000   0.000000   11.500000
2722       0  0.00   0.000000   0.000000    1.900000
2723       1  0.00   0.000000   0.000000    0.000000
2724       0  0.00   0.000000   0.000000  191.300003

[2725 rows x 5 columns]

In [ ]:
y=crim.pop("narr86")

In [ ]:
x=np.c_[np.ones(len(crim)),crim.to_numpy()]

In [ ]:
reg=regresionlineal(x,y)

In [ ]:
reg.beta()

array([ 0.59387489, -0.16243696, -0.00618803,  0.00771062, -0.00243615])

In [ ]:
reg.errore()

array([[0.02585771],
       [0.04081609],
       [0.01238073],
       [0.009432  ],
       [0.00024321]])

In [ ]:
reg.testadistico()

array([[ 22.9670375 ],
       [ -3.97972866],
       [ -0.49981111],
       [  0.81749603],
       [-10.01685265]])

In [ ]:
reg.intervaloc()

0.5431937864640133 0.6445559915485397
0.513875355198571 0.673874422813982
0.5696086527549122 0.6181411252576408
0.5753881694511137 0.6123616085614393
0.5933982067819197 0.5943515712306333


la proporcion de cadenas anteriores al aumentar, Es esta una variable probablemente significativa, siendo negativa con el numero de veces que esta persona sea arrestado.
el promedio en tiempo de la cadena no es significativo
el tiempo en prision desde los 18 meses no es significativa
los ingresos legales son significativos,  apartir de estos disminuye la probabilidad de ser arrestado

In [ ]:
crim=wd.data("crime1")

In [ ]:
crim=crim[["narr86","pcnv","avgsen","tottime","inc86","pcnvsq", "inc86sq"]]

In [ ]:
crim

narr86  pcnv     avgsen    tottime       inc86  pcnvsq       inc86sq
0          0  0.38  17.600000  35.200001    0.000000  0.1444      0.000000
1          2  0.44   0.000000   0.000000    0.800000  0.1936      0.640000
2          1  0.33  22.799999  22.799999    0.000000  0.1089      0.000000
3          2  0.25   0.000000   0.000000    8.800000  0.0625     77.440002
4          1  0.00   0.000000   0.000000    8.100000  0.0000     65.610008
...      ...   ...        ...        ...         ...     ...           ...
2720       1  0.00   0.000000   0.000000    0.000000  0.0000      0.000000
2721       0  0.00   0.000000   0.000000   11.500000  0.0000    132.250000
2722       0  0.00   0.000000   0.000000    1.900000  0.0000      3.610000
2723       1  0.00   0.000000   0.000000    0.000000  0.0000      0.000000
2724       0  0.00   0.000000   0.000000  191.300003  0.0000  36595.691406

[2725 rows x 7 columns]

In [ ]:
y=crim.pop("narr86")

In [ ]:
x=np.c_[np.ones(len(crim)),crim.to_numpy()]

In [ ]:
reg=regresionlineal(x,y)

In [ ]:
reg.beta()

array([ 5.77523688e-01,  6.22634460e-01, -6.92546885e-03,  4.48874198e-03,
       -4.08083748e-03, -8.26588291e-01,  8.56614968e-06])

In [ ]:
reg.errore()

array([[2.99333383e-02],
       [1.54837099e-01],
       [1.22801963e-02],
       [9.36604874e-03],
       [5.29688653e-04],
       [1.56660748e-01],
       [2.13246317e-06]])

In [ ]:
reg.testadistico()

array([[19.29366122],
       [ 4.02122271],
       [-0.56395425],
       [ 0.47925674],
       [-7.70421918],
       [-5.27629479],
       [ 4.01702116]])

In [ ]:
reg.intervaloc()

0.5188543446272484 0.6361930306175203
0.2740429732330809 0.8810044020116878
0.5534545028666766 0.6015928723780921
0.5591662320894251 0.5958811431553437
0.5764854978617464 0.5785618773830223
0.27046862064489136 0.8845787545998773
0.5775195079945737 0.577527867250195
